spring:
  rabbitmq:
    host: 129.211.164.41
    port: 5672
    virtual-host: lkz
    username: user
    password: 123456
#    publisher-confirm-type: correlated  #开启消息到达交互机的确认机制
#    publisher-returns: true      #消息由交互机到达队列时失败触发

server:
  port: 8888