server:
  port: 9014

# 消费者的组名
apache.rocketmq.consumer.PushConsumer: orderConsumer
# 生产者的组名
apache.rocketmq.producer.producerGroup: Producer
# NameServer地址
apache.rocketmq.namesrvAddr: 127.0.0.1:9876