server:
  port: 8011

spring:
  redis:
    database: 1
    host: 139.196.37.168
    port: 6379
  #连接池最大连接数（使用负值表示没有限制）默认8
    lettuce:
      pool:
        max-active: 8
  #连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
        max-wait: -1
  #连接池中的最大空闲连接默认8
        max-idle: 8
  #连接池中的最小空闲连接默认0
        min-idle: 0
    password: 123456
