server:
  port: 9010
spring:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: root
  password: root
  type: com.alibaba.druid.pool.DruidDataSource